### ISSUE TITLE
error: package com.leonteqsecurity.anonymousdial.Services does not exist import com.leonteqsecurity.anonymousdial.Services.MakeCall;                                                  ^

### ISSUE THREAD

**Issue by hamza0786** [leonTech254/AnonymousDial#1]
Hi getting this error:
error: package com.leonteqsecurity.anonymousdial.Services does not exist
import com.leonteqsecurity.anonymousdial.Services.MakeCall;
                                                 ^

**Comment by leonTech254** [comment]
Sorry for the delay. The issue has been fixed. Kindly pull the latest changes.
